### ISSUE TITLE
can't mass-assign protected attributes with rails 3.2.3

### ISSUE THREAD

**Issue by vikrammishra333** [spoiledmilk/casein3#1]
Hi,
while generating a user(admin) using the command rake casein:users:create_admin email=abc@example.com, i got the following error:-

rake aborted!
Can't mass-assign protected attributes: login, name, email, access_level, password, password_confirmation

Tasks: TOP => casein:users:create_admin

As per my understanding, rails 3.2 raise exception on mass assignment protection for Active Record models, which may lead to above error.
Now, I think i have two options to alleviate from this error:-
1) create the model "user.rb" and mention the attributes as attr_accessible. OR
2) Comment the line " config.active_record.mass_assignment_sanitizer = :strict" in development.rb file.

Which one is good for casein, please suggest me.

Thanks in Advance

**Comment by vikrammishra333** [comment]
Sorry to say but option(1) didn't work for me and although option(2) worked but now the command rake casein:users:create_admin email=abc@example.com gives another error

[Casein] Failed: check that the 'admin' account doesn't already exist.

while there is no any users in DB yet.

**Comment by russellquinn** [comment]
Hey there,

You need to change the value of whitelist_attributes in application.rb to 'false', instead of the default 'true'

config.active_record.whitelist_attributes = false

This should get the current version of Casein working with Rails 3.2.3, but note that the whitelist will now be disabled for all models (see http://guides.rubyonrails.org/security.html#mass-assignment)

**Comment by vikrammishra333** [comment]
Thanks russel....it worked.. :)

**Comment by ghost** [comment]
Thanks Russel For Giving the correct and exact information, Thank you.

**Comment by russellquinn** [comment]
This is fixed in Casein 4.x

https://github.com/russellquinn/casein

**Comment by KeeyaWangJones** [comment]
When I added Casein to an existing project, I did get this error. I actually had to add the entire code line because it did not exist in the project at all: config.active_record.whitelist_attributes = false. The info you provided fixed the problem! Thanks Russel!

**Comment by russellquinn** [comment]
Are you using Casein 4.x?

**Comment by KeeyaWangJones** [comment]
I apologize for the delay.
I am using gem 'casein', '~>5.0.0'
I hope that helps!

**Comment by russellquinn** [comment]
If you use the scaffolding generator, then this will automatically create a list of allowable parameters in the controller, so you don't need to just whitelist everything.

**Comment by KeeyaWangJones** [comment]
The scaffold generated from Casein looks good. It is when I tried to generate an admin that did not work until I added the whitelist in the project's development.rb with the rest of the config statements. I think it is because it was an existing project and is ultimately setup differently. When I use Casein as a new rails app, I did not have the problem.

**Comment by yxlwfds** [comment]
rake casein:users:create_admin email=xxx@.com password="ssddaa"
[Casein] Failed: check that the 'admin' account doesn't already exist.
Casein5.1.1 rails4.2.4

**Comment by russellquinn** [comment]
This is the wrong project for Casein 5.x tickets.

Latest Casein:
https://github.com/russellquinn/casein

**Comment by russellquinn** [comment]
Also, I can confirm that creating an admin user works with Casein 5.1.1 and Rails 4.2.4. Are you sure the 'admin' account doesn't already exist?
